version: v3
data_local_save_dir: ./data/raw
dvc_remote_repo: https://github.com/iamabhi6345/cyber_bullying_detection_dvc.git
dvc_data_folder: data/raw
github_user_name: iamabhi6345
github_access_token_secret_id: abhishek-data-github-access-token
infrastructure:
  project_id: cyberbullying-428016
  zone: asia-south1-a
  network: default
dataset_reader_manager:
  _target_: abhishek.data_processing.dataset_readers.DatasetReaderManager
  dataset_readers:
    ghc:
      _target_: abhishek.data_processing.dataset_readers.GHCDatasetReader
      dataset_dir: ./data/raw/ghc
      dataset_name: ghc
      gcp_project_id: cyberbullying-428016
      gcp_github_access_token_secret_id: abhishek-data-github-access-token
      dvc_remote_repo: https://github.com/iamabhi6345/cyber_bullying_detection_dvc.git
      github_user_name: iamabhi6345
      version: v3
      dev_split_ratio: 0.3
    jtc:
      _target_: abhishek.data_processing.dataset_readers.JigsawToxicCommentsDatasetReader
      dataset_dir: ./data/raw/jogsaw-toxic-comments
      dataset_name: jtc
      gcp_project_id: cyberbullying-428016
      gcp_github_access_token_secret_id: abhishek-data-github-access-token
      dvc_remote_repo: https://github.com/iamabhi6345/cyber_bullying_detection_dvc.git
      github_user_name: iamabhi6345
      version: v3
      dev_split_ratio: 0.06
    twitter:
      _target_: abhishek.data_processing.dataset_readers.TwitterDatasetReader
      dataset_dir: ./data/raw/twitter
      dataset_name: twitter
      gcp_project_id: cyberbullying-428016
      gcp_github_access_token_secret_id: abhishek-data-github-access-token
      dvc_remote_repo: https://github.com/iamabhi6345/cyber_bullying_detection_dvc.git
      github_user_name: iamabhi6345
      version: v3
      dev_split_ratio: 0.25
      test_split_ratio: 0.2
  repartition: true
  available_memory: null
dataset_cleaner_manager:
  _target_: abhishek.data_processing.dataset_cleaners.DatasetCleanerManager
  dataset_cleaners:
    stop_words:
      _target_: abhishek.data_processing.dataset_cleaners.StopWordsDatasetCleaner
    to_lower_case:
      _target_: abhishek.data_processing.dataset_cleaners.ToLowerCaseDatasetCleaner
    url:
      _target_: abhishek.data_processing.dataset_cleaners.URLDatasetCleaner
    punctuation:
      _target_: abhishek.data_processing.dataset_cleaners.PunctuationDatasetCleaner
      punctuation: '!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~'
    non_letters:
      _target_: abhishek.data_processing.dataset_cleaners.NonLettersDatasetCleaner
    new_line:
      _target_: abhishek.data_processing.dataset_cleaners.NewLineCharacterDatasetCleaner
    non_ascii:
      _target_: abhishek.data_processing.dataset_cleaners.NonASCIIDatasetCleaner
    referance:
      _target_: abhishek.data_processing.dataset_cleaners.ReferanceToAccountDatasetCleaner
    re_tweet:
      _target_: abhishek.data_processing.dataset_cleaners.ReTweetDatasetCleaner
    spell_correction:
      _target_: abhishek.data_processing.dataset_cleaners.SpellCorrectionDatasetCleaner
      spell_correction_model:
        _target_: abhishek.utils.utils.SpellCorrectionModel
        max_dictionary_edit_distance: 2
        prefix_length: 7
        count_threshold: 1
dask_cluster:
  _target_: dask_cloudprovider.gcp.GCPCluster
  n_workers: 1
  projectid: cyberbullying-428016
  zone: asia-south1-a
  network: default
  network_projectid: cyberbullying-428016
  machine_type: n2-standard-2
  source_image: projects/ubuntu-os-cloud/global/images/ubuntu-minimal-2004-focal-v20220203
  docker_image: asia-south1-docker.pkg.dev/cyberbullying-428016/abhishek/abhishek-data-processing:5ec70e7c-8933-41ae-94ed-6cfcf2649e35
  docker_args: '--log-driver=gcplogs

    '
  extra_bootstrap:
  - gcloud auth configure-docker --quiet asia-soutj1-docker.pkg.dev
  ngpus: 0
  gpu_type: null
  filesystem_size: 50
  disk_type: pd-standard
  on_host_maintenance: TERMINATE
  worker_class: dask.distributed.Nanny
  worker_options:
    nthreads: 1
  env_vars: {}
  scheduler_options: {}
  silence_logs: null
  asynchronous: null
  security: true
  preemptible: false
  debug: false
  instance_labels: null
processed_data_save_dir: gs://cyberbullying45/data/processed/{run_tag}
docker_image_name: asia-south1-docker.pkg.dev/cyberbullying-428016/abhishek/abhishek-data-processing
docker_image_tag: 5ec70e7c-8933-41ae-94ed-6cfcf2649e35
run_tag: default_run
min_nrof_words: 2
