version: v3
data_local_save_dir: ./data/raw
dvc_remote_repo: https://github.com/iamabhi6345/cyber_bullying_detection_dvc.git
dvc_data_folder: data/raw
github_user_name: iamabhi6345
github_access_token_secret_id: abhishek-data-github-access-token
infrastructure:
  project_id: cyberbullying-428016
  zone: asia-south1-a
  network: default
dataset_reader_manager:
  _target_: abhishek.data_processing.dataset_readers.DatasetReaderManager
  dataset_readers:
    ghc:
      _target_: abhishek.data_processing.dataset_readers.GHCDatasetReader
      dataset_dir: ./data/raw/ghc
      dataset_name: ghc
      gcp_project_id: cyberbullying-428016
      gcp_github_access_token_secret_id: abhishek-data-github-access-token
      dvc_remote_repo: https://github.com/iamabhi6345/cyber_bullying_detection_dvc.git
      github_user_name: iamabhi6345
      version: v3
      dev_split_ratio: 0.3
    jtc:
      _target_: abhishek.data_processing.dataset_readers.JigsawToxicCommentsDatasetReader
      dataset_dir: ./data/raw/jogsaw-toxic-comments
      dataset_name: jtc
      gcp_project_id: cyberbullying-428016
      gcp_github_access_token_secret_id: abhishek-data-github-access-token
      dvc_remote_repo: https://github.com/iamabhi6345/cyber_bullying_detection_dvc.git
      github_user_name: iamabhi6345
      version: v3
      dev_split_ratio: 0.06
    twitter:
      _target_: abhishek.data_processing.dataset_readers.TwitterDatasetReader
      dataset_dir: ./data/raw/twitter
      dataset_name: twitter
      gcp_project_id: cyberbullying-428016
      gcp_github_access_token_secret_id: abhishek-data-github-access-token
      dvc_remote_repo: https://github.com/iamabhi6345/cyber_bullying_detection_dvc.git
      github_user_name: iamabhi6345
      version: v3
      dev_split_ratio: 0.25
      test_split_ratio: 0.2
  repartition: true
  available_memory: 3750000000.0
dataset_cleaner_manager:
  _target_: abhishek.data_processing.dataset_cleaners.DatasetCleanerManager
  dataset_cleaners:
    stop_words:
      _target_: abhishek.data_processing.dataset_cleaners.StopWordsDatasetCleaner
    to_lower_case:
      _target_: abhishek.data_processing.dataset_cleaners.ToLowerCaseDatasetCleaner
    url:
      _target_: abhishek.data_processing.dataset_cleaners.URLDatasetCleaner
    punctuation:
      _target_: abhishek.data_processing.dataset_cleaners.PunctuationDatasetCleaner
      punctuation: '!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~'
    non_letters:
      _target_: abhishek.data_processing.dataset_cleaners.NonLettersDatasetCleaner
    new_line:
      _target_: abhishek.data_processing.dataset_cleaners.NewLineCharacterDatasetCleaner
    non_ascii:
      _target_: abhishek.data_processing.dataset_cleaners.NonASCIIDatasetCleaner
    referance:
      _target_: abhishek.data_processing.dataset_cleaners.ReferanceToAccountDatasetCleaner
    re_tweet:
      _target_: abhishek.data_processing.dataset_cleaners.ReTweetDatasetCleaner
    spell_correction:
      _target_: abhishek.data_processing.dataset_cleaners.SpellCorrectionDatasetCleaner
      spell_correction_model:
        _target_: abhishek.utils.utils.SpellCorrectionModel
        max_dictionary_edit_distance: 2
        prefix_length: 7
        count_threshold: 1
dask_cluster:
  _target_: dask.distributed.LocalCluster
  n_workers: 8
  memory_limit: auto
  processes: true
  threads_per_worker: 1
  scheduler_port: 8786
  silence_logs: 30
  host: null
  dashboard_address: :8787
  asynchronous: false
  blocked_handlers: null
  service_kwargs: null
  security: null
  protocol: null
  interface: null
  worker_class: null
processed_data_save_dir: ./data/processed
docker_image_name: asia-south1-docker.pkg.dev/cyberbullying-428016/abhishek/abhishek-data-processing
docker_image_tag: 33defb93-0d9a-4483-8c22-4a0540d948fa
